
site_name: Avance de Proyecto de Programación de Modelos Probabilísticos

nav:
  - Inicio: index.md
  - Gráfcas descriptivas y modelos de probabilidad: graficas_descriptivas_modelos_probabilidad.md
  - Momentos: momentos_var1_var2.md
  - Instrucciones: instrucciones.md


theme: 
  name: material
  language: es
  palette:
    primary: purple
  logo: img/plot.png
  favicon: img/plot.png
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - toc.integrate
    - content.tooltips
    - content.code.copy
    - pymdownx.arithmatex

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - md_in_html
  - footnotes
  - abbr
  - attr_list

  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

